### ISSUE TITLE
Actualización en el servicio del webservice v1.3

### ISSUE THREAD

**Issue by TheSpectroMx** [phpcfdi/sat-estado-cfdi#11]
A partir del 18 de diciembre de 2020 se actualiza el servicio de validación por medio del webservice en su versión 1.3 donde se agrega **"ValidacionEFOS"** el cual tendrá como resultado **"ValidacionEFOS=100"** (se encontró en listado EFOS) o **"ValidacionEFOS=200"** (No se encontró en listado EFOS)

**Comment by eclipxe13** [comment]
Gracias por la información. Ya he hecho esta adecuación y cambios a todo el proyecto: revisión de documentación, ejemplos, documentación en español, entorno de desarrollo, etc. Con lo que se ha hecho el PR #14 y alcanzado la versión 1.0.0.
