### ISSUE TITLE
Estado CFDI de retención

### ISSUE THREAD

**Issue by anikilator5001** [phpcfdi/sat-estado-cfdi#15]
Usando la libreria phpcfdi/sat-estado-cfdi y la phpcfdi/cfdi-expresiones para obtener la expresión funciona correctamente con CFDI's de Ingreso, Egreso, Pago, Nomina y Traslado; pero cuando se trata de un CFDI de Retención la función de "$cfdiStatus->query()->isFound()" me devuelve "false", lo cual quiere decir que el SAT no sabe del CFDI con la expresión dada.

No se si el problema está en la expresión devuelta por la librería phpcfdi/cfdi-expresiones (Por seguridad cambié los RFC's de la expresión y el UUID por letras "X"):
"?re=XXXXXXXXXXXX&rr=XXXXXXXXXXXXX&tt=0000204766.700000&id=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"

**Comment by eclipxe13** [comment]
Hemos hecho algunas pruebas y parece que el web service de consulta de estado en su versión actual 1.3 no entrega el estado de un *"CFDI de Retenciones e información de pagos"*.

Debería hacerlo, porque lo único que solicita es la *expresión*, sin embargo, el SAT ha separado en su estructura tecnológica los CFDI regulares de los CFDI de retenciones, así que creemos en la comunidad que simplemente no ha expuesto este servicio públicamente para este tipo de CFDI, o tal vez no lo ha creado, porque su mecanismo de cancelación es diferente del de los CFDI regulares.

Otra posibilidad es que la expresión esté mal formada, sin embargo este no parece ser el caso. Hemos probado con expresiones creadas manualmente para asegurarnos que la expresión no es el problema y al hacer la consulta devuelve un estado de no encontrado.

Como alternativas:

- Se puede consultar manualmente el estado de un CFDI de retenciones en <https://prodretencionverificacion.clouda.sat.gob.mx/>. La consulta está protegida por un captcha.
- Se puede consultar manualmente en el portal de CFDI de retenciones en <https://prodretencioncontribuyente.clouda.sat.gob.mx/>. Requiere iniciar sesión con clave CIEC y resolver un captcha.
- Se puede consultar de forma automatizada usando el web service de descarga masiva, descargando los metadatos, con la librería [`phpcfdi/sat-ws-descarga-masiva`](https://github.com/phpcfdi/sat-ws-descarga-masiva).

**Comment by anikilator5001** [comment]
Muchas gracias por la aclaración y las posibles soluciones. Esperemos que en un futuro cercano el SAT haga disponible el servicio para consultar los de CFDI de retención.

**Comment by eclipxe13** [comment]
Por si alguien llega con este mismo problema: La librería https://github.com/phpcfdi/sat-estado-retenciones sirve para poder obtener el estado (vigente o cancelado y la demás información) del CFDI de Retenciones e Información de Pagos.
