### ISSUE TITLE
I realize that the documentation does not show the same as the code.

### ISSUE THREAD

**Issue by blacktrue** [phpcfdi/sat-estado-cfdi#7]
Hi

The documentation does not show the same as the code. for example:

Posibles estados:

`CodigoEstatus: query(): QueryStatus.`

found: Si el estado inicia con S - .
notFound: en cualquier otro caso.

`Estado: document(): DocumentStatus.`

active: Si el estado reportó Vigente.
cancelled: Si el estado reportó Cancelado.
notFound: en cualquier otro caso.

The correct is:

`CodigoEstatus: request(): QueryStatus.`

found: Si el estado inicia con S - .
notFound: en cualquier otro caso.

`Estado: active(): DocumentStatus.`

active: Si el estado reportó Vigente.
cancelled: Si el estado reportó Cancelado.
notFound: en cualquier otro caso.

**Comment by eclipxe13** [comment]
Thank you!

Looks like previous intent to give correct names to classes and properties where only partially done.

This affects methods:
- `QueryStatus::request()` to be renamed to `QueryStatus::query()`
- `QueryStatus::active()` to be renamed to `QueryStatus::document()`

I will create a version `0.6.1` that will deprecate and throw `E_USER_DEPRECATION` errors, so anyone using version `^0.6.0"` on its composer will receive this upgrade. No breaking changes will be made, only notices.

Next, I will create a version `0.7.0` that removes deprecated methods.

I'm working on it, I think that today will be fixed.

**Comment by eclipxe13** [comment]
Will be closed until version 0.7.0 is created

**Comment by eclipxe13** [comment]
Done!
